import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_BASE_URL||"http://localhost:8000";
async function j(url,opt={}){const r=await fetch(API+url,opt);if(!r.ok)throw new Error((await r.text())||r.statusText);return r.json()}
function App(){const[projects,setProjects]=useState([]),[sel,setSel]=useState(null),[name,setName]=useState(""),[aud,setAud]=useState(""),[goal,setGoal]=useState("Leads und Verkäufe"),[tone,setTone]=useState("professionell, klar, vertrauenswürdig"),[base,setBase]=useState("http://host.docker.internal:11434"),[model,setModel]=useState("qwen3:latest"),[msg,setMsg]=useState("Bereit"),[brief,setBrief]=useState("");
const load=async()=>{const p=await j("/api/projects");setProjects(p);if(sel){const n=p.find(x=>x.id===sel.id);if(n)setSel(n)}};useEffect(()=>{load()},[]);
const cfg=()=>({ollama:{base_url:base,model},additional_context:""});
async function create(){try{setMsg("Erstelle Projekt…");const p=await j("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,audience:aud,goal,tone})});setSel(p);setName("");await load();setMsg("Projekt erstellt")}catch(e){setMsg(e.message)}}
async function upload(e){if(!sel)return;const fd=new FormData();[...e.target.files].forEach(f=>fd.append("files",f));try{setMsg("Upload…");await j("/api/projects/"+sel.id+"/upload",{method:"POST",body:fd});await load();setMsg("Dateien hochgeladen")}catch(x){setMsg(x.message)}}
async function test(){try{setMsg("Teste Ollama…");const r=await j("/api/ollama/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({base_url:base,model})});setMsg("Ollama OK: "+(r.models?.join(", ")||"keine Modelle"))}catch(e){setMsg(e.message)}}
async function mkBrief(){try{setMsg("Generiere Marketing-Brief…");const r=await j("/api/projects/"+sel.id+"/generate-brief",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(cfg())});setBrief(r.brief);await load();setMsg("Brief fertig")}catch(e){setMsg(e.message)}}
async function mkSite(){try{setMsg("Generiere Landingpage…");await j("/api/projects/"+sel.id+"/generate-site",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(cfg())});await load();setMsg("Website fertig")}catch(e){setMsg(e.message)}}
async function open(p){setSel(p);setBrief("");if(p.has_brief)try{setBrief((await j("/api/projects/"+p.id+"/brief")).brief)}catch{}}
return <div className="app"><aside><div className="brand">Marketing Studio</div><p className="muted">AI Content → Conversion Website</p><button className="ghost" onClick={()=>setSel(null)}>+ Neues Projekt</button><div className="list">{projects.map(p=><button key={p.id} className={sel?.id===p.id?"active":""} onClick={()=>open(p)}><b>{p.name}</b><small>{p.files?.length||0} Dateien · {p.has_site?"Website fertig":p.has_brief?"Brief fertig":"Neu"}</small></button>)}</div></aside>
<main><header><div><h1>{sel?sel.name:"Neues Marketing-Projekt"}</h1><p>{msg}</p></div><div className="ollama"><input value={base} onChange={e=>setBase(e.target.value)} placeholder="Ollama URL"/><input value={model} onChange={e=>setModel(e.target.value)} placeholder="Modell"/><button onClick={test}>Verbindung testen</button></div></header>
{!sel?<section className="card form"><h2>Projekt anlegen</h2><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Zielgruppe<input value={aud} onChange={e=>setAud(e.target.value)}/></label><label>Ziel<input value={goal} onChange={e=>setGoal(e.target.value)}/></label><label>Ton<input value={tone} onChange={e=>setTone(e.target.value)}/></label><button className="primary" disabled={!name.trim()} onClick={create}>Projekt erstellen</button></section>:
<div className="grid"><section className="card"><h2>1. Quellen</h2><p>PDF, DOCX, TXT oder Markdown hochladen.</p><input type="file" multiple accept=".pdf,.docx,.txt,.md,.markdown" onChange={upload}/><div className="chips">{sel.files?.map(f=><span key={f}>{f}</span>)}</div></section>
<section className="card"><h2>2. Marketing-Brief</h2><p>Ollama analysiert Angebot, Zielgruppe, Nutzen, Einwände, SEO und Conversion-Struktur.</p><button className="primary" onClick={mkBrief}>Brief generieren</button></section>
<section className="card"><h2>3. Landingpage</h2><p>Aus dem Brief wird eine responsive Marketing-Website erzeugt.</p><button className="primary" disabled={!sel.has_brief} onClick={mkSite}>Website generieren</button>{sel.has_site&&<a className="btn" href={API+"/api/projects/"+sel.id+"/download"}>HTML herunterladen</a>}</section>
<section className="card wide"><h2>Marketing-Brief</h2><pre>{brief||"Noch kein Brief generiert."}</pre></section>
{sel.has_site&&<section className="card wide"><h2>Website Preview</h2><iframe sandbox="allow-scripts" src={API+"/api/projects/"+sel.id+"/preview"}/></section>}</div>}</main></div>}
createRoot(document.getElementById("root")).render(<App/>);